services:
  backend_postgres:
    image: postgres:18-alpine
    container_name: backend_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: social_media
    ports:
      - "5432:5432"
    volumes:
      - backend_postgres_data:/var/lib/postgresql/18/data

  backend_mongo:
    image: mongo:latest
    container_name: backend_mongo
    ports:
      - "27017:27017"
    volumes:
      - backend_mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: backend_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  backend_postgres_data:
  backend_mongo_data:
  rabbitmq_data:
