name: Run tests
on: "push"

jobs:
  build: # Name of the job
    runs-on: own
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
          pnpm run test